repos:
  - repo: local
    hooks:
      - id: precommit-check
        name: Run precommit.sh checks
        entry: ./pre-commit.sh
        language: script
        pass_filenames: false
        always_run: true